In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
import warnings
warnings.filterwarnings('ignore')

# chi sqaure test 

In [6]:
data = sns.load_dataset("tips")

In [8]:
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [16]:
data[['sex','smoker']]

sex smoker
0    Female     No
1      Male     No
2      Male     No
3      Male     No
4    Female     No
..      ...    ...
239    Male     No
240  Female    Yes
241    Male    Yes
242    Male     No
243  Female     No

[244 rows x 2 columns]

In [18]:
# summerization of data using crosstab

In [24]:
data_table = pd.crosstab(data['sex'] , data['smoker'])

In [26]:
data_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [28]:
observed_values= data_table.values

In [30]:
observed_values


array([[60, 97],
       [33, 54]], dtype=int64)

In [34]:
import scipy.stats as stats


In [42]:
stat_test , p , dof, expected_val = stats.chi2_contingency(observed_values)

In [44]:
expected_val


array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [46]:
#using chi sqaure critical values
dof = 1

In [48]:
from scipy.stats import chi2

In [58]:
for i in zip(observed_values , expected_val):
    print(i)

(array([60, 97], dtype=int64), array([59.84016393, 97.15983607]))
(array([33, 54], dtype=int64), array([33.15983607, 53.84016393]))


In [ ]:
stats.ch